# Generated by Django 5.0.6 on 2024-05-26 11:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=155)),
                ('cover', models.ImageField(upload_to='medias/book/covers/')),
                ('description', models.TextField()),
                ('book', models.FileField(upload_to='medias/book/books/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('book_author', models.CharField(db_index=True, default='Unknown', max_length=60)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('changed', models.BooleanField(default=False)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
