# Generated by Django 5.0.6 on 2024-05-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
