# Generated by Django 5.0.6 on 2024-05-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_views_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='views_count',
            new_name='view_count',
        ),
    ]
